DEFINE_MESSAGE(0x0001, TEXTBOX_TYPE_BLUE, TEXTBOX_POS_BOTTOM,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (EN)" COLOR(DEFAULT) QUICKTEXT_DISABLE
,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (DE)" COLOR(DEFAULT) QUICKTEXT_DISABLE
,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (FR)" COLOR(DEFAULT) QUICKTEXT_DISABLE
)

#define DEFINE_MESSAGE_EN(textId, type, yPos, nesMessage)                                                      \
    DEFINE_MESSAGE(                                                                                            \
        textId, type, yPos, nesMessage,                                                                        \
        UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (DE)" COLOR(DEFAULT) QUICKTEXT_DISABLE, \
        UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (FR)" COLOR(DEFAULT) QUICKTEXT_DISABLE)

DEFINE_MESSAGE_EN(2, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "After a long day of adventuring..." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(3, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... Link is eager to get some rest." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(4, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "As the night is falling..." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(5, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... Link encounters an inn." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(6, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "He pays for a room until morning..." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(7, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... and heads to his night quarters." QUICKTEXT_DISABLE
)





#ifdef DEFINE_MESSAGE_FFFC
DEFINE_MESSAGE(0xFFFC, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
"0123456789\n"
"ABCDEFGHIJKLMN\n"
"OPQRSTUVWXYZ\n"
"abcdefghijklmn\n"
"opqrstuvwxyz\n"
" -.\n"
,
,
)
#endif

DEFINE_MESSAGE(0xFFFD, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
""
,
""
,
""
)
