DEFINE_MESSAGE(0x0001, TEXTBOX_TYPE_BLUE, TEXTBOX_POS_BOTTOM,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (EN)" COLOR(DEFAULT) QUICKTEXT_DISABLE
,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (DE)" COLOR(DEFAULT) QUICKTEXT_DISABLE
,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (FR)" COLOR(DEFAULT) QUICKTEXT_DISABLE
)





#ifdef DEFINE_MESSAGE_FFFC
DEFINE_MESSAGE(0xFFFC, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
"0123456789\n"
"ABCDEFGHIJKLMN\n"
"OPQRSTUVWXYZ\n"
"abcdefghijklmn\n"
"opqrstuvwxyz\n"
" -.\n"
,
,
)
#endif

DEFINE_MESSAGE(0xFFFD, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
""
,
""
,
""
)
