DEFINE_MESSAGE(0x0001, TEXTBOX_TYPE_BLUE, TEXTBOX_POS_BOTTOM,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (EN)" COLOR(DEFAULT) QUICKTEXT_DISABLE
,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (DE)" COLOR(DEFAULT) QUICKTEXT_DISABLE
,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (FR)" COLOR(DEFAULT) QUICKTEXT_DISABLE
)

#define DEFINE_MESSAGE_EN(textId, type, yPos, nesMessage)                                                      \
    DEFINE_MESSAGE(                                                                                            \
        textId, type, yPos, nesMessage,                                                                        \
        UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (DE)" COLOR(DEFAULT) QUICKTEXT_DISABLE, \
        UNSKIPPABLE QUICKTEXT_ENABLE COLOR(RED) "MISSING MESSAGE DATA! (FR)" COLOR(DEFAULT) QUICKTEXT_DISABLE)

DEFINE_MESSAGE_EN(2, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "After a long day of adventuring..." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(3, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... Link is eager to get some rest." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(4, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "As the night is falling..." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(5, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... Link encounters an inn." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(6, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "He pays for a room until morning..." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(7, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... and heads to his night quarters." QUICKTEXT_DISABLE
)


DEFINE_MESSAGE_EN(100, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "You found a key!\nIt can open a locked door." QUICKTEXT_DISABLE
)

/*
z<-o  oot world axes
   |
 x v

courtyard graves layout

 0
1
2     5 7
3         6
     8
4         9
*/

// 8 and 9: push 9
DEFINE_MESSAGE_EN(200, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nOf the two facing each other,\ndo not disturb the one near the wall." QUICKTEXT_DISABLE
)

// pull 0
DEFINE_MESSAGE_EN(201, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nThe one nearest to the coffins\nshould be troubled." QUICKTEXT_DISABLE
)

// forbidden
// pull 4
DEFINE_MESSAGE_EN(202, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nBother the one closest to the library." QUICKTEXT_DISABLE
)

// 0, 1, 2, 3: push at least two
DEFINE_MESSAGE_EN(203, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried, four side by side.\nAt least two of them\nshould be left in peace." QUICKTEXT_DISABLE
)

// forbidden
// 0, 1, 2, 3: any one may not be surrounded by two pushed ones (one on each side)
DEFINE_MESSAGE_EN(204, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried, four side by side.\nNo one may be surrounded on both\nsides by harmony." QUICKTEXT_DISABLE
)

// 0, 1, 2, 3: there may not be 2 pulled ones side by side
DEFINE_MESSAGE_EN(205, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried, four side by side.\nA troubled one may not be a neighbour\nto another one of its kind." QUICKTEXT_DISABLE
)

// pull 8 (near the tree)
DEFINE_MESSAGE_EN(206, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nDisturb the one near what is dead\nyet not buried." QUICKTEXT_DISABLE
)

// push 5 (has mc poppies)
DEFINE_MESSAGE_EN(207, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nShow respect where flowers bloom." QUICKTEXT_DISABLE
)

// forbidden
// pull 6 (slower to push/pull)
DEFINE_MESSAGE_EN(208, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nTrouble the one carrying\nheavy misdeeds." QUICKTEXT_DISABLE
)

// forbidden
// 5 and 7: set 7 like 5 (push)
DEFINE_MESSAGE_EN(209, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Ten souls lie buried.\nThe two closest to the tower\nshould not be separated." QUICKTEXT_DISABLE
)


DEFINE_MESSAGE_EN(0x300, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Link, you triggered a curse!" QUICKTEXT_DISABLE
TEXTID("\x03\x01")
)

DEFINE_MESSAGE_EN(0x301, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "This shadow of yourself\ndoes not seem aggressive..." QUICKTEXT_DISABLE
TEXTID("\x03\x02")
)

DEFINE_MESSAGE_EN(0x302, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "... but it is " COLOR(RED) "bound to your movements" COLOR(RED) "." QUICKTEXT_DISABLE
TEXTID("\x03\x03")
)

DEFINE_MESSAGE_EN(0x303, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "You have to get rid of it\nin order to move freely!" QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(0x400, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "There is no lock in sight,\nbut the door doesn't open.\nIt must be a very special mechanism." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(0x401, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "The door is open!\nBut the tower may be unsafe,\nyou should find " COLOR(RED) "a weapon" COLOR(DEFAULT) " \nbefore heading in." QUICKTEXT_DISABLE
)

DEFINE_MESSAGE_EN(0x402, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "The door is open!\nAre you ready to go up the tower?\n"
TWO_CHOICE COLOR(ADJUSTABLE) "Let's go!\n"
"No..." COLOR(DEFAULT)
QUICKTEXT_DISABLE
)

// [0x500;0x600) is reserved for credits

DEFINE_MESSAGE_EN(0x600, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Hey Link, you're finally awake." QUICKTEXT_DISABLE
TEXTID("\x06\x01")
)

DEFINE_MESSAGE_EN(0x601, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "I resemble a fairy,\nbut I am only a manifestation\nof the " COLOR(YELLOW) "Triforce of courage" COLOR(DEFAULT) "'s power." QUICKTEXT_DISABLE
TEXTID("\x06\x02")
)

DEFINE_MESSAGE_EN(0x602, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "An " COLOR(RED) "evil Poe" COLOR(DEFAULT) " cast a curse on you,\nbut you were protected\nby the " COLOR(YELLOW) "Triforce of courage" COLOR(DEFAULT) "." QUICKTEXT_DISABLE
TEXTID("\x06\x03")
)

DEFINE_MESSAGE_EN(0x603, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "Now we are trapped\nin the world of this " COLOR(RED) "evil Poe" COLOR(DEFAULT) ".\nWe must find a way out!" QUICKTEXT_DISABLE
)


DEFINE_MESSAGE_EN(0x700, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(DEFAULT) "You defeated the " COLOR(RED) "evil Poe" COLOR(DEFAULT) "!\nCongratulations!\nNow you will have a peaceful night!" QUICKTEXT_DISABLE
TEXTID("\x07\x01")
)

DEFINE_MESSAGE_EN(0x701, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "== Credits ==" COLOR(DEFAULT) QUICKTEXT_DISABLE
TEXTID("\x07\x02")
)

DEFINE_MESSAGE_EN(0x702, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Made by Team Dampé's Hut\nDragorn421, Tharo,\nmaia090, rankaisija, sklitte22" COLOR(DEFAULT) QUICKTEXT_DISABLE
TEXTID("\x07\x03")
)

DEFINE_MESSAGE_EN(0x703, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Tools:\nBlender, fast64" COLOR(DEFAULT) QUICKTEXT_DISABLE
TEXTID("\x07\x04")
)

DEFINE_MESSAGE_EN(0x704, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Source:\nhttps://github.com/Dampes-Hut/escaperoom" COLOR(DEFAULT) QUICKTEXT_DISABLE
TEXTID("\x07\x05")
)

DEFINE_MESSAGE_EN(0x705, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "This mod is available free of charge.\nIf you paid for it, you got scammed." COLOR(DEFAULT) QUICKTEXT_DISABLE
TEXTID("\x07\x06")
)

DEFINE_MESSAGE_EN(0x706, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_MIDDLE,
UNSKIPPABLE QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Thanks for playing!" COLOR(DEFAULT) QUICKTEXT_DISABLE
)


#ifdef DEFINE_MESSAGE_FFFC
DEFINE_MESSAGE(0xFFFC, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
"0123456789\n"
"ABCDEFGHIJKLMN\n"
"OPQRSTUVWXYZ\n"
"abcdefghijklmn\n"
"opqrstuvwxyz\n"
" -.\n"
,
,
)
#endif

DEFINE_MESSAGE(0xFFFD, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
""
,
""
,
""
)
