DEFINE_MESSAGE(0x0500, TEXTBOX_TYPE_CREDITS, TEXTBOX_POS_VARIABLE,
QUICKTEXT_ENABLE "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
SHIFT("\x24")  SHIFT("\x12") "MISSING MESSAGE DATA! (CREDITS)\n"
"\n"
"\n"
SHIFT("\x24")  SHIFT("\x36") "" QUICKTEXT_DISABLE  FADE2("\x00\x32")
)
