#ifndef ESCAPEROOM_CUTSCENES_H
#define ESCAPEROOM_CUTSCENES_H

enum InnPaintingActorCueId {
    INNPAINTING_CUEID_POE_UNFREEZE,
    INNPAINTING_CUEID_POE_EXITPAINTING,
    INNPAINTING_CUEID_POE_CASTCURSE,
    INNPAINTING_CUEID_LINK_TRIFORCE,
    INNPAINTING_CUEID_POE_SURPRISED,
    INNPAINTING_CUEID_NOOP
};

#endif
