// #define DEFINE_ACTOR(name, enum, allocType, nameString)

DEFINE_ACTOR(InnPainting, ACTOR_INN_PAINTING, ACTOROVL_ALLOC_NORMAL, "InnPainting")
DEFINE_ACTOR(ChandelierLight, ACTOR_CHANDELIER_LIGHT, ACTOROVL_ALLOC_NORMAL, "ChandelierLight")
DEFINE_ACTOR(Lights_Out, ACTOR_LIGHTS_OUT, ACTOROVL_ALLOC_NORMAL, "Lights_Out")
DEFINE_ACTOR(PropFlame, ACTOR_PROP_FLAME, ACTOROVL_ALLOC_NORMAL, "PropFlame")
