// #define DEFINE_ENTRANCE(enum, sceneId, spawn, continueBgm, displayTitleCard, endTransType, startTransType)

DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_1, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_2, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_3, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
