// #define DEFINE_ENTRANCE(enum, sceneId, spawn, continueBgm, displayTitleCard, endTransType, startTransType)

DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_1, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_2, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_3, SCENE_INN_BEDROOM, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_INN_BEDROOM_0_4, SCENE_INN_BEDROOM, 0, true, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

DEFINE_ENTRANCE(ENTR_TEST_DARKLINK_PUZZLE_0,   SCENE_TEST_DARKLINK_PUZZLE, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_TEST_DARKLINK_PUZZLE_0_1, SCENE_TEST_DARKLINK_PUZZLE, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_TEST_DARKLINK_PUZZLE_0_2, SCENE_TEST_DARKLINK_PUZZLE, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_TEST_DARKLINK_PUZZLE_0_3, SCENE_TEST_DARKLINK_PUZZLE, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

DEFINE_ENTRANCE(ENTR_TEST_DANCEFLOOR_0, SCENE_TEST_DANCEFLOOR, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_TEST_DANCEFLOOR_0_1, SCENE_TEST_DANCEFLOOR, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_TEST_DANCEFLOOR_0_2, SCENE_TEST_DANCEFLOOR, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
DEFINE_ENTRANCE(ENTR_TEST_DANCEFLOOR_0_3, SCENE_TEST_DANCEFLOOR, 0, false, false, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

DEFINE_ENTRANCE(ENTR_MAINMAP_COURTYARD_COFFIN,   SCENE_MAINMAP, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_MAINMAP_COURTYARD_COFFIN_1, SCENE_MAINMAP, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_MAINMAP_COURTYARD_COFFIN_2, SCENE_MAINMAP, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_MAINMAP_COURTYARD_COFFIN_3, SCENE_MAINMAP, 0, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

DEFINE_ENTRANCE(ENTR_MAINMAP_DBG_LIBRARY,   SCENE_MAINMAP, 1, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_MAINMAP_DBG_LIBRARY_1, SCENE_MAINMAP, 1, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_MAINMAP_DBG_LIBRARY_2, SCENE_MAINMAP, 1, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
DEFINE_ENTRANCE(ENTR_MAINMAP_DBG_LIBRARY_3, SCENE_MAINMAP, 1, false, false, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
